
from dataclasses import dataclass
from typing import Iterable


@dataclass(slots=True)
class Game:
    

    def __str__(self):...

    def __repr__(self):...

    def __getitem__(self, pos: Iterable[int]):...

    def __setitem__(self, pos: Iterable[int], piece):...

    def __delitem__(self, pos: Iterable[int]):...

    def update_check(self):...

    def move_is_legal(self, pos, piece):...

    def update_piece_lm(self, piece):...

    def update_legal_moves(self):...

    def update_right_castle(self, piece):...

    def update_en_passant(self, pos, piece):...